config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  namespace :ajax do
    post 'recipe/text_nodes'
    get 'foods/all'
    get 'count_types/all'
    post 'profile/currency'
  end

  scope :my do
    get 'profile' => 'users/profile#index', as: :my_profile
    get 'edit/password' => 'users/profile#edit_password', as: :edit_password
    patch 'edit/password' => 'users/profile#update_password', as: :update_password

    scope :recipes do
      get 'new' => 'recipe#new', as: :recipe_new
      get '' => 'recipe#my_list', as: :recipe_list
      get ':id/edit' => 'recipe#edit', as: :recipe_edit
      post '' => 'recipe#create', as: :recipe_create
      patch ':id' => 'recipe#update', as: :recipe_update
      delete ':id' => 'recipe#delete'

      get 'watched' => 'recipe#watched', as: :watched_recipe_list
      # id here actually is recipe_id
      get 'likes' => 'wanted_recipe#list', as: :wanted_recipe_list
      post 'likes/:id' => 'wanted_recipe#create', as: :wanted_recipe
      delete 'likes/:id' => 'wanted_recipe#delete'
    end
  end

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
      :registrations => "users/registrations",
      :sessions => "users/sessions"

  }, path: "my"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'search' => 'permalink#search', as: :search
  get ':slug' => 'permalink#show1', as: :permalink

  root 'static#landing'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_prices
  has_many :recipes
  has_and_belongs_to_many :wanted_recipes, :join_table => :favourite_recipes, class_name: "Recipe",
                          foreign_key: :user_id, association_foreign_key: :recipe_id
  has_and_belongs_to_many :watched_recipes, :join_table => :watched_recipes, class_name: "Recipe",
                          foreign_key: :user_id, association_foreign_key: :recipe_id


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  validates_presence_of :email
  has_many :authorizations
  mount_uploader :image, UserImageUploader

  def full_name
    fname.present? && lname.present? ? ( "#{fname} #{lname}" ) : (fname.present? ? fname : email)
  end

  def in_wanted? recipe
    wanted_recipes.include? recipe
  end

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :secret => auth.credentials.secret).first_or_initialize
    authorization.token = auth.credentials.token
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
      if user.blank?
        user = User.new
        user.password = Devise.friendly_token[0,10]
        user.fname = auth.info.first_name
        user.lname = auth.info.last_name
        user.email = auth.info.email.nil? ? Devise.friendly_token[0,10] + '@no.mail' : auth.info.email
        user = self.send("fetch_user_from_#{auth.provider.downcase}", auth, user)
        user.save
      end
      authorization.username = auth.info.nickname
      authorization.user_id = user.id
      authorization.save
    end
    authorization.user
  end

  protected

  def self.fetch_user_from_vkontakte auth, user
    user.remote_image_url = auth.extra.raw_info.photo_200_orig
    user
  end

  def self.fetch_user_from_facebook auth, user
    # user.remote_image_url = auth.info.image.to_s
    user
  end

end

app/controllers/ajax/profile_controller.rb
class Ajax::ProfileController < ApplicationController

  def currency
    # authenticate_user!
    set_currency params[:currency]

    render json: { status: :success }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	skip_before_filter :authenticate_user!
	def all
		logger.info "omniauth controller"
    logger.info env["omniauth.auth"]
		user = User.from_omniauth(env["omniauth.auth"], current_user)

		if user.persisted?
			flash[:success] = t 'registration.complete'
      sign_in_and_redirect2(user)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to stored_location_for(:user)
		end
	end

	  def failure
      #handle you logic here..
      #and delegate to super.
      super
   end


  alias_method :facebook, :all
  alias_method :vkontakte, :all
	# alias_method :twitter, :all
	# alias_method :linkedin, :all
	# alias_method :github, :all
	# alias_method :passthru, :all
	# alias_method :google_oauth2, :all

  def sign_in_and_redirect2(resource_or_scope, *args)
    options  = args.extract_options!
    scope    = Devise::Mapping.find_scope!(resource_or_scope)
    resource = args.last || resource_or_scope
    sign_in(scope, resource, options)
    redirect_to stored_location_for(:user) || root_path # thanks_for_registration_path
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def orders
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_attributes(params.required(:user).permit(:password, :password_confirmation, :current_password))
      # Sign in the user by passing validation in case their password changed
      sign_in :user, @user, :bypass => true
      redirect_to my_profile_path
    else
      render :edit_password
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # add_crumb "My profile", :edit_user_registration_path, :only => :edit

  def new
    @body_class = 'registration-page'
    super
  end

  def update
    @user = current_user
    # user_params = params[:user]

    if user_params[:current_password].blank?
      user_params.delete(:current_password)
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
      if @user.update_attributes(user_params)
        sign_in @user, :bypass => true
        redirect_to edit_user_registration_path
      else
        flash[:alert] = 'Ошибка'
        render :edit
      end
    else
      if @user.update_with_password(user_params)
        sign_in @user, :bypass => true
        redirect_to edit_user_registration_path
      else
        flash[:alert] = 'Ошибка'
        render :edit
      end
    end
  end

  protected

  def after_sign_up_path_for resource
    @cart.try(:update!, user: resource)
    stored_location_for(:user) || root_path
  end

  def user_params
    params.require(:user).permit :current_password, :password, :password_confirmation,
                                 :email, :fname, :lname,
                                 address_attributes:
                                     [:phone, :email, :username, :address ]
  end

  def sign_up_params
    user_params
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  # add_crumb "My profile", :edit_user_registration_path, :only => :edit

  def new
    @body_class = 'registration-page'
    super
  end

  protected
  def after_sign_in_path_for resource
    @cart.try(:update!, user: resource)
    super resource
  end

end

app/views/users/profile/_address_form.html.slim
- address = f.object
- is_user_edit = defined?(is_user_edit) ? is_user_edit : false

.form-group
  = f.label :phone, class: 'form-label', required: address.validate_saving?
  span
    = f.full_error :phone
  = f.input_field :phone, class: 'form-control'

.form-group
  = f.label :address, class: 'form-label', required: address.validate_saving?
  span
    = f.full_error :address
  = f.input_field :address, class: 'form-control'

- unless is_user_edit
  .form-group
    = f.label :username, class: 'form-label'
    span
      = f.full_error :username
    = f.input_field :username, class: 'form-control'

  .form-group
    = f.label :email, class: 'form-label'
    span
      = f.full_error :email
    = f.input_field :email, class: 'form-control'

app/views/users/profile/_left_menu.html.slim
ul
  li class="#{params[:action] == 'index' ? 'active' : ''}"
    a href=my_profile_path Мої замовлення
  li class="#{params[:action] == 'edit' ? 'active' : ''}"
    a href=edit_user_registration_path Мої дані
  li class="#{params[:action] == 'edit_password' ? 'active' : ''}"
    a href=edit_password_path Мій пароль

app/views/users/profile/edit_password.html.slim
h2 Змінити пароль

.row
  .col-xs-12.col-sm-4.col-md-3
    = render 'users/profile/left_menu'
  .col-xs-12.col-sm-8.col-md-9
    = simple_form_for @user, url: update_password_path do |f|
      .clearfix
      .form-group
        = f.label :password, class: 'form-label', required: true
        span
          = f.full_error :password
        = f.input_field :password, class: 'form-control', autocomplete: "off"

      .form-group
        = f.label :password_confirmation, class: 'form-label', required: true
        span
          = f.full_error :password_confirmation
        = f.input_field :password_confirmation, class: 'form-control', autocomplete: "off"

      .clearfix
      = render 'form/save_btn', btn: 'Змінити пароль'
    .clearfix

app/views/users/profile/index.html.slim
h2 #{current_user.full_name}
img src=current_user.image.url