config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  namespace :ajax do
    post 'recipe/text_nodes'
    get 'foods/all'
    get 'count_types/all'
    post 'profile/currency'
  end

  scope :my do
    get 'profile' => 'users/profile#index', as: :my_profile
    get 'edit/password' => 'users/profile#edit_password', as: :edit_password
    patch 'edit/password' => 'users/profile#update_password', as: :update_password

    scope :recipes do
      get 'new' => 'recipe#new', as: :recipe_new
      get '' => 'recipe#my_list', as: :recipe_list
      get ':id/edit' => 'recipe#edit', as: :recipe_edit
      post '' => 'recipe#create', as: :recipe_create
      patch ':id' => 'recipe#update', as: :recipe_update
      delete ':id' => 'recipe#delete'

      get 'watched' => 'recipe#watched', as: :watched_recipe_list
      # id here actually is recipe_id
      get 'likes' => 'wanted_recipe#list', as: :wanted_recipe_list
      post 'likes/:id' => 'wanted_recipe#create', as: :wanted_recipe
      delete 'likes/:id' => 'wanted_recipe#delete'
    end
  end

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
      :registrations => "users/registrations",
      :sessions => "users/sessions"

  }, path: "my"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'search' => 'permalink#search', as: :search
  get ':slug' => 'permalink#show1', as: :permalink

  root 'static#landing'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # extend FriendlyId
  # friendly_id :title, use: [:slugged, :finders]

  belongs_to :user
  has_and_belongs_to_many :recipe_tags, :join_table => :recipe_to_tag
  has_many :components, :dependent => :destroy
  has_many :recipe_text_nodes, :dependent => :destroy
  has_one :food_value, as: :nutritionable, :dependent => :destroy

  accepts_nested_attributes_for :recipe_tags
  accepts_nested_attributes_for :components, :food_value, :recipe_text_nodes, allow_destroy: true

  mount_uploader :image, RecipeImageUploader

  validates :title, presence: true
  after_initialize :create_food_value

  scope :landing, -> do
    order('created_at desc')
  end

  def self.search(str)
    return [] if str.blank?
    words = str.split

    cond_text = words.map{|w| " title LIKE ? "}.join(" OR ") + ' OR '
    cond_values = words.map{|w| "%#{w}%"}

    cond_text = cond_text + words.map{|w| " recipe_text_nodes.text LIKE ? "}.join(" OR ")
    cond_values = cond_values + words.map{|w| "%#{w}%"}
    joins(:recipe_text_nodes).where(str ? [cond_text, *cond_values] : []).order('created_at desc').uniq
  end

  def meta_title
    "#{title} | #{Settings.seo.title_sufix}"
  end

  def og_image
    image.url(:list)
  end

  def og_description
    "#{title} | #{Settings.seo.title_sufix} на сайте #{Settings.seo.og_hostname}"
  end

  def kg= value
    value = value.gsub(',', '.')
    write_attribute(:kg, value)
  end

  def show_next_recipe
    Recipe.order("id asc").find_by("id > ?", id)
  end

  def show_prev_recipe
    Recipe.order("id desc").find_by("id < ?", id)
  end

  protected
  def create_food_value
    self.food_value = FoodValue.new if food_value.nil?
  end
end

app/controllers/ajax/recipe_controller.rb
class Ajax::RecipeController < ApplicationController

  def text_nodes
    node = RecipeTextNode.new image_params

    render :json => { cache: node.image_cache }
  end

  protected
  def image_params
    params.permit(:image)
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  before_filter :authenticate_user!
  # before_action :set_food_selects, exept: [:list, :update]

  def new
    @recipe = Recipe.new
    @recipe_json = recipe_json @recipe
  end

  def create
    @recipe = Recipe.new new_recipe_params
    @recipe.user = current_user
    @recipe_json = recipe_json @recipe

    if @recipe.save
      redirect_to permalink_path(@recipe), flash: {notice: t('recipe.created')}
    else
      render 'new'
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
    @recipe_json = recipe_json @recipe

    render 'new'
  end

  def update
    @recipe = current_user.recipes.find(params[:id])

    @recipe.assign_attributes new_recipe_params

    if @recipe.save
      redirect_to permalink_path(@recipe), flash: {notice: t('recipe.updated')}
    else
      set_food_selects
      render 'new'
    end
  end

  def delete
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy

    redirect_to root_path, flash: {notice: t('recipe.deleted')}
  end

  def my_list
    set_menu :my_recipes
    @recipes = current_user.recipes
  end

  def watched
    set_menu :watched
    @recipes = current_user.watched_recipes
  end

  protected

  def set_food_selects
    @foods = Food.all.includes(:food_weights)
    @foods_json = @foods.to_json include: [:food_price, :food_weights, :food_value]
  end

  def recipe_params
    params.require(:recipe).permit(
        :title, :text, :kg, :duration, :image, :image_cache, :remove_image, recipe_tag_ids:[],
        components_attributes: [ :count, :food_id, :count_type, :_destroy, :id],
        food_value_attributes: [:id, :energy, :protein, :fat, :sugar, :sugar_index ],
        recipe_text_nodes_attributes: [:id, :node, :text, :image, :image_cache, :remove_image, :_destroy ]
    )
  end

  def new_recipe_params
    new_recipe_hash = recipe_params
    new_recipe_hash[:text] = ActionView::Base.white_list_sanitizer.sanitize new_recipe_hash[:text]
    new_recipe_hash[:components_attributes].each do |c|
      c = c[1]
      if c[:food_id].to_i == 0 || Food.find_by(id: c[:food_id].to_i).nil?
        food = Food.create name: c[:food_id], user: current_user, is_moderated: false
        c[:food_id] = food.id
      end
    end

    new_recipe_hash
  end
end

app/views/recipe/_component_show_list_item.html.slim
- ng = defined?(ng) ? ng : false
/- TODO -t
- if ng
  div ng-repeat="component in recipe.components"
    span ng-bind="component.food().name" #{component.food.name}
    | &nbsp;&mdash;&nbsp;
    span
      span ng-bind="component.count" #{component_count component.count}
      | &nbsp;
      span ng-bind="t('ru.count_type.' + component.count_type)" #{t_count_type component.count_type}

- else
  div ng-show="false"
    span #{component.food.name}
    | &nbsp;&mdash;&nbsp;
    span
      span #{component_count component.count}
      | &nbsp;
      span #{t_count_type component.count_type}

app/views/recipe/_currency_dialog.html.slim
.hide
  #currency-dialog.text-center
    div - Ваша валюта <br> российский рубль (RUB)?
    a.btn.btn-sm.btn-success ng-click="saveCurrency('RUB')" Да, рубль (RUB)
    br
    br
    | - Нет, моя валюта
    br
    a.btn.btn-xs.btn-success ng-click="saveCurrency('UAH')" Гривна (UAH)
    br
    a.btn.btn-xs.btn-success ng-click="saveCurrency('BYR')" Белорусский рубль (BYR)
    br

app/views/recipe/_list.html.slim
.recipe-list
  - recipes.each do |recipe|
    - edit = can? :edit, recipe
    - 1.times do
      .col-xs-4.col-md-3.col-lg-2-4.col-xlg-2.recipe-item
        - if edit
          .overlay.ui-views-count
            a href=recipe_edit_path(recipe)
              .text-center
                span.ui-views-count
                  i.fa.fa-pencil
                  br
                  | Изменить
        a href=permalink_path(recipe)
          .img-wr
            .components class="#{recipe_slide_class}"
              ul
                - i = 0
                - max = 6
                - recipe.components.each do |component|
                  - i = i + 1
                  - if i <= max
                    li
                      nobr #{component.food.name} - #{component_count component.count} #{t_count_type(component.count_type)}
                - if recipe.components.count > max
                  - left = recipe.components.count - max
                  li ... и еще #{left} #{Russian.p(left, "компонент", "компонента", "компонентов")}

            img.img-responsive src=recipe.image.url(:list_square)

          span.title #{recipe.title}
          .clearfix
          .tags
            - if recipe.recipe_tags.count > 0
              span #{recipe.recipe_tags[0].name}
            span.pull-right #{recipe.views_count} #{Russian.p(recipe.views_count, "просмотр", "просмотра", "просмотров")}

app/views/recipe/create.html.slim
h1 Recept#create
p Find me in app/views/recipe/create.html.slim

app/views/recipe/delete.html.slim
h1 Recept#delete
p Find me in app/views/recipe/delete.html.slim

app/views/recipe/edit.html.slim
h1 Recept#edit
p Find me in app/views/recipe/edit.html.slim

app/views/recipe/index.html.slim
= content_for :wide
  = render 'recipe_tag/left_menu'

  .main-content-postioner
    .main-content-wrapper
      .main-content
        h2 #{@recipe_tag.name}
        = render 'recipe/list', recipes: @recipes

        .clearfix
        .col-xs-12
          = paginate @recipes

app/views/recipe/my_list.html.slim
= content_for :wide
  = render 'recipe_tag/left_menu'

  .main-content-postioner
    .main-content-wrapper
      .main-content
        h2 Мои вкусняшки
        = render 'recipe/list', recipes: @recipes, edit: true

        .clearfix

app/views/recipe/new.html.slim
br
.recipe-form-action ng-controller="vMainCore"
  div ng-controller="vMain"
    - if @recipe.persisted?
      .pull-right
        a.btn.btn-danger.btn-xs href=recipe_update_path(@recipe) data-method="delete"
          i.fa.fa-times
          | Удалить
      .clearfix

    meta angular-load="v-recipe-form"
    script type="application/json" rid-settings="foods" angular-load-json="/ajax/foods/all"
    script type="application/json" rid-settings="countTypes" angular-load-json="/ajax/count_types/all"
    script type="application/json" rid-settings="currency_data"
      | #{{currency_data.to_json}}
    script type="application/json" rid-settings="recipe"
      | #{{@recipe_json}}

    .angular-loader
      = render 'layouts/loader'

    = simple_form_for @recipe ? @recipe : Recipe.new, url: @recipe.persisted? ? recipe_update_path(@recipe) : recipe_create_path, html: { class: 'angular-hide-on-load v-recipe-form-el' } do |f|
      .hide
        = f.simple_fields_for :food_value do |fvf|
          = fvf.input :protein, input_html: { 'value' => "{{recipe.food_value_in_100('protein')}}" }
          = fvf.input :fat, input_html: { 'value' => "{{recipe.food_value_in_100('fat')}}" }
          = fvf.input :sugar, input_html: { 'value' => "{{recipe.food_value_in_100('sugar')}}" }
          = fvf.input :energy, input_html: { 'value' => "{{recipe.food_value_in_100('energy')}}" }
          = fvf.input :sugar_index
      .form-group.row
        .col-xs-3
          = f.full_error :image
          .img-cache-wr
            .img-cache-placeholder ng-show="recipe.show_image_placeholder()"
              i.fa.fa-image
              br
              span.img-label выбрать картинку
            .img-cache-placeholder.edit ng-show="!recipe.show_image_placeholder()"
              i.fa.fa-edit
            img.img-cache.img-responsive ng-src="{{ recipe.get_image() }}" ng-show="!recipe.show_image_placeholder()"

            .hide
              = f.input_field :image, as: :file, 'rid-image-file' => '', 'image-src' => 'recipe.image._base64', 'image-closest-drop' => '.img-cache-wr'
              = f.input_field :image_cache

        .col-xs-4
          .row
            .col-xs-12
              = f.label :title, class: 'form-label'
              span
                = f.full_error :title
                = f.input_field :title, class: 'form-control', autofocus: true, required: true
            .col-xs-12
              = f.label :recipe_tags, class: 'form-label'
              span
                = f.full_error :recipe_tags
                = f.input_field :recipe_tag_ids, as: :select, collection: RecipeTag.all, multiple: true, 'rid-select2' => ''
        .col-xs-5
          .row
            .form-group.col-xs-12.text-right.duration-group
              = f.label :duration, class: 'form-label'
              = f.input_field :duration, class: 'form-control'
              | мин.
              span
                = f.full_error :duration

            .form-group.col-xs-12.text-right
              = f.label :kg, class: 'form-label'
              = f.input_field :kg, class: 'form-control'
              | кг.
              span
                = f.full_error :kg
            .clearfix

      div
        .row
          .col-xs-6
            label.form-label Инградиенты:
          .col-xs-6
            a.btn.btn-success.btn-xs.pull-right ng-click="newComponentView()"
              span ng-show="component_views[_tmp.component_view] == 'none'" Покзывать состав иградиентов
              span ng-show="component_views[_tmp.component_view] == 'component'" Показать состав рецепта
              span ng-show="component_views[_tmp.component_view] == 'recipe'" Скрыть состав

        .row
          .recipe-form-component-list ng-class="{ 'active-components' : component_views[_tmp.component_view] == 'component' }"
            .component-item.form-group ng-repeat="component in recipe.components" ng-hide="component._destroy"
              .hide
                input type="checkbox" name="recipe[components_attributes][{{ $index }}][_destroy]" ng-model="component._destroy"
                input type="hidden" name="recipe[components_attributes][{{ $index }}][id]" value="{{ component.id }}"
              .col.remove-link-col
                a.remove-link rel="nofollow" ng-click="removeComponent(component)"
                  i.fa.fa-times-circle-o
                .index
                  | {{ $index + 1 }})
              .col.name-col.dashed
                input type="text" name="recipe[components_attributes][{{ $index }}][food_id]" ng-model="component.food_id" v-recipe-select2-new=""
              .dash-col &mdash;
              .col.count-col
                input.form-control.dashed type="text" v-recipe-count="" ng-model="component.count" name="recipe[components_attributes][{{ $index }}][count]"
              .col.count-type-col.dashed
                input type="text" v-recipe-select2-count-type="" component="component" ng-model="component.count_type" name="recipe[components_attributes][{{ $index }}][count_type]"
              .col.component-price-col ng-if="component.cost() > 0.001"
                | &nbsp;=&nbsp;
                span.line ng-bind="component.cost()"
                | &nbsp;
                span.active-text v-recipe-currency="#currency-dialog" ng-bind="currencyLabel()"

              .col.component-values-col.line ng-show="component_views[_tmp.component_view] == 'component'"
                .col-xs-3
                  span ng-bind="component.food_value('energy')"
                  span &nbsp;ккал
                .col-xs-3
                  b белки:&nbsp;
                  span ng-bind="component.food_value('protein')"
                  span &nbsp;гр.
                .col-xs-3
                  b жиры:&nbsp;
                  span ng-bind="component.food_value('fat')"
                  span &nbsp;гр.
                .col-xs-3
                  b углеводы:&nbsp;
                  span ng-bind="component.food_value('sugar')"
                  span &nbsp;гр.
              .clearfix

            .form-group.text-center ng-show2="!_tmp.show_component_value"
              a.btn.btn-primary rel="nofollow" ng-click="addComponent()"
                i.fa.fa-plus
                | Добавить инградиент
              .clearfix
            .clearfix

          .component-recipe-values-col.pull-right.form-group.hidden-xs.hidden-sm ng-show="component_views[_tmp.component_view] == 'recipe'"
            table.table
              thead
                tr
                  th colspan="2" Всего:
              tbody
                tr
                  td вес
                  td
                    span ng-bind="recipe.weight()"
                    | &nbsp;кг
                tr
                  td стоимость
                  td
                    span ng-bind="recipe.cost()"
                    | &nbsp;
                    span.active-text ng-bind="currencyLabel()" v-recipe-currency="#currency-dialog"
                tr
                  td калорий
                  td
                    span ng-bind="recipe.food_value('energy')"
                    | &nbsp;ккал
              thead
                tr
                  th colspan="2" В 100гр:
              tbody
                tr
                  td калорийность
                  td
                    span ng-bind="recipe.food_value_in_100('energy')"
                    | &nbsp;ккал
                tr
                  td белки
                  td
                    span ng-bind="recipe.food_value_in_100('protein')"
                    | &nbsp;гр
                tr
                  td жиры
                  td
                    span ng-bind="recipe.food_value_in_100('fat')"
                    | &nbsp;гр
                tr
                  td углеводы
                  td
                    span ng-bind="recipe.food_value_in_100('sugar')"
                    | &nbsp;гр
            .clearfix

        .clearfix

      .form-group
        label.form-label Приготовление:
        div ng-repeat="text_node in recipe.recipe_text_nodes track by $index"
          = render 'recipe/new/text_nodes'

        .clearfix

        i.fa.fa-plus.add-text-node-label
        a.btn.btn-primary.btn-add-node ng-click="addImageNode()" title="Добавить картинку" apply-tooltip=""
          i.fa.fa-image
        a.btn.btn-primary.btn-add-node ng-click="addTextNode()" title="Добавить текст" apply-tooltip=""
          i.fa.fa-quote-left

      .clearfix

      .form-group.text-center
        button.btn.btn-primary type="submit"
          span ng-show="isSubmited"
            i.fa.fa-spinner.fa-spin
            | Загружаем картинки и готовим вкусняшку)
          span ng-show="!isSubmited"
            i.fa.fa-cutlery
            | Сохранить рецепт
        |&nbsp;&nbsp;&nbsp;
        a.btn.btn-primary ng-show="!isSubmited" href=(@recipe.persisted? ? recipe_edit_path(@recipe) : recipe_new_path) rel="nofollow"
          i.fa.fa-undo
          | Ааа, верните как было :)

        .clearfix


    = render 'recipe/currency_dialog'

app/views/recipe/search.html.slim
= content_for :wide
  = render 'recipe_tag/left_menu'

  .main-content-postioner
    .main-content-wrapper
      .main-content
        h2 Поиск "#{params[:q]}"
        = render 'recipe/list', recipes: @recipes

        .clearfix

app/views/recipe/show.html.slim
= content_for :gray_navbar
  .gray-navbar.recipe-show-action
    .container
      .row
        .col-xs-3
          - next_recipe = @recipe.show_next_recipe
          - prev_recipe = @recipe.show_prev_recipe
          - if prev_recipe
            a.btn.btn-success.btn-sm apply-click-on-key-up2="37" rel="nofollow" apply-tooltip="" title=prev_recipe.title href=permalink_path(prev_recipe)
              i.fa.fa-chevron-left
          - if next_recipe && prev_recipe
            | &nbsp;&nbsp;
          - if next_recipe
            a.btn.btn-success.btn-sm apply-click-on-key-up2="39" rel="nofollow" apply-tooltip="" title=next_recipe.title href=permalink_path(next_recipe)
              i.fa.fa-chevron-right

        .col-xs-5
          - @recipe.recipe_tags.each do |tag|
            a.btn.btn-success.btn-xs href=permalink_path(tag) #{tag.name}

        .col-xs-4
          span.pull-right
            span.ui-views-count
              i.fa.fa-eye
              br
              | #{@recipe.views_count}
            noindex
              - if current_user.nil? || (current_user && !current_user.in_wanted?(@recipe))
                a.btn.btn-sm.btn-success rel="nofollow" href=wanted_recipe_path(@recipe) data-method="post"
                  i.fa.fa-star
                  | В избранное
              - else
                - if current_user.in_wanted?(@recipe)
                  a.btn.btn-sm.btn-success.active rel="nofollow" href=wanted_recipe_path(@recipe) data-method="delete"
                    i.fa.fa-star
                    | Уже в избранном
              - if can? :edit, @recipe
                a.edit-link.btn.btn-success.btn-sm href=recipe_edit_path(@recipe)
                  i.fa.fa-pencil
                  | Изменить

.recipe-show-action ng-controller="vMainCore"
  div ng-controller="vShow"
    = render 'recipe/currency_dialog'

    meta angular-load="v-recipe-show"
    /script type="application/json" rid-settings="foods" angular-load-json="/ajax/foods/all"
    script type="application/json" rid-settings="countTypes" angular-load-json="/ajax/count_types/all"
    script type="application/json" rid-settings="currency_data"
      | #{{currency_data.to_json}}
    script type="application/json" rid-settings="recipe"
      | #{{@recipe_json}}

    .angular-loader
      = render 'layouts/loader'

    .v-recipe-show.angular-hide-on-load.row
      .clearfix

      .col-xs-12
        h2.text-center
          | #{@recipe.title}

      .col-xs-12.col-sm-6.col-md-4
        a rel="nofollow" data-lightbox="image-1" href=@recipe.image.url
          img.img-responsive src=@recipe.image.url alt=@recipe.title
        .visible-sm
          div
            br
            b
              i.fa.fa-pie-chart
              span &nbsp;В 100гр:
          div
            | калорийность - #{@recipe.food_value.energy} ккал, белки - #{@recipe.food_value.protein} гр, жиры #{@recipe.food_value.fat}гр, углеводы #{@recipe.food_value.sugar} гр

      .col-xs-12.col-sm-6.col-md-8
        .row
          .col-xs-12.col-md-6
            - if @recipe.duration
              div
                i.fa.fa-clock-o
                b &nbsp;Время приготовления:&nbsp;
                | #{@recipe.duration} мин.
                br
            div
              /i.fa.fa-lemon-o
              i.fa.fa-puzzle-piece
              b &nbsp;Инградиенты:
            div
              - @recipe.components.each_with_index do |component, index|
                = render 'recipe/component_show_list_item', ng: index == 0, component: component

          .col-xs-12.col-md-6
            b.text-left
              i.fa.fa-calculator
              span &nbsp;Всего получится:

            noindex.text-right
              a.btn.btn-success.btn-xs.pull-right ng-click="restore()" rel="nofollow" ng-show="!_is_new"
                i.fa.fa-undo
                | Сбросить

            div.multiply-weight ng-show="_tmp.weight > 0"
              span data-placement="auto right" apply-tooltip="" title="Измени на то, сколько ты хочеш приготовить!"
                i.fa.fa-pencil
                input.culc-input.text-center ng-model="_tmp.weight" ng-change="calcWeight()"
                span кг&nbsp;&nbsp;
                span.active-text apply-tooltip="" title="Вдвое больше!" ng-click="multiplyWeight(2)" x2
                span.active-text apply-tooltip="" title="Тройная порция" ng-click="multiplyWeight(3)" x3
                span.active-text apply-tooltip="" title="Поменьше" ng-click="multiplyWeight(0.5)" ÷2


            div ng-show="_tmp.cost > 0"
              span data-placement="auto right" apply-tooltip="" title="Измени на то, сколько ты хочеш потратить!"
                i.fa.fa-pencil
                input.culc-input.text-center ng-model="_tmp.cost" ng-change="calcCost()"
                span.active-text v-recipe-currency="#currency-dialog" ng-bind="currencyLabel()"

            div ng-show="_tmp.food_value_energy > 0"
              span data-placement="auto right" apply-tooltip="" title="Измени, если следиш за каллориями!"
                i.fa.fa-pencil
                input.culc-input.text-center ng-model="_tmp.food_value_energy" ng-change="calcEnergy()"
                | ккал

            - if @recipe.food_value.usefull?
              .hidden-sm
                div
                  br
                  b
                    i.fa.fa-pie-chart
                    span &nbsp;В 100гр:

                div
                  | калорийность - #{@recipe.food_value.energy} ккал, белки - #{@recipe.food_value.protein} гр, жиры #{@recipe.food_value.fat}гр, углеводы #{@recipe.food_value.sugar} гр

      .clearfix
      .col-xs-12
        div.text-center
          br
          b
            i &mdash;&nbsp;&nbsp;
            /i.fa.fa-cutlery
            i.fa.fa-cutlery
            i  Приготовление &mdash;
          br
          br

        - @recipe.recipe_text_nodes.each do |text_node|
          .recipe-text-node
            - if text_node.node == 'image'
              .col-xs-12.col-sm-4.col-lg-3.col-lg-offset-2.text-right
                i
                  | #{{text_node.text}}
              .col-xs-12.col-sm-8.col-lg-6
                img.img-responsive src=text_node.image.url
              hr.visible-xs
            - if text_node.node == ''
              .col-xs-12
                | #{{text_node.text}}
            .clearfix

app/views/recipe/update.html.slim
h1 Recept#update
p Find me in app/views/recipe/update.html.slim

app/views/recipe/watched.html.slim
= content_for :wide
  = render 'recipe_tag/left_menu'

  .main-content-postioner
    .main-content-wrapper
      .main-content
        h2 Просмотренные
        = render 'recipe/list', recipes: @recipes

        .clearfix